env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
